Test/Models/User.cs
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Test.Models
{
    public class User : IdentityUser
    {
        
        public ICollection<Session> Sessions { get; set; }
        [Required(ErrorMessage = "Write first name")]
        [Display(Name = "First name")]
        public string firstName { get; set; }
        [Required(ErrorMessage = "Write last name")]
        [Display(Name = "Last name")]
        public string lastName { get; set; }
        public User()
        {
            Sessions = new List<Session>();
        }
    }
}

Test/Controllers/MenuController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test.Models;
using static Test.Models.ViewModels;

namespace Test.Controllers
{
    [Authorize]
    public class MenuController : Controller
    {
        private TestContext db = new TestContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Users()
        {
            return View();
        }
        public ActionResult Report()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ReportOfMonth(DateTime date)
        {
            List<Session> sessions = db.Sessions.Include(s => s.User).Where(s => s.TimeLogin.Month == date.Month).ToList();
            ICollection<TimeFlag> timeFlags = new List<TimeFlag>();
            //Add flags
            foreach(var session in sessions)
            {
                if(session.UserId != null)
                {
                    timeFlags.Add(new TimeFlag { Time = session.TimeLogin, Login = true, UserId = session.User.Id });
                    timeFlags.Add(new TimeFlag { Time = Convert.ToDateTime(session.TimeLogout), Login = false, UserId = session.User.Id });
                }
            }
            //Sort flags
            timeFlags = timeFlags.OrderBy(f => f.Time).ToList();
            //Take first and last day of month
            var firstDayOfMonth = new DateTime(date.Year, date.Month, 1);
            var lastDayOfMonth = firstDayOfMonth.AddMonths(1).AddDays(-1);
            Week[] weeks = new Week[5];
            for (int week = 0; week <= 4; week++)
            {
                int day = 1;
                int MaxUsers;
                weeks[week] = new Week();
                weeks[week].Monday = new DateTime(date.Year, date.Month, day + (week * 7)).ToString("d");
                while(day <= 7 && day + (week * 7) <= lastDayOfMonth.Day)
                {
                    MaxUsers = MaxUsersPerDay(timeFlags.Where(f => f.Time.Day == (day + week * 7)).ToList());
                    if (weeks[week].MaxUsers < MaxUsers)
                        weeks[week].MaxUsers = MaxUsers;
                    day++;
                }
            }
            return PartialView(weeks);
        }
        public struct TimeFlag
        {
            public DateTime Time { get; set; }
            public bool Login { get; set; }
            public string UserId { get; set; }
        }
       
        public int MaxUsersPerDay(List<TimeFlag> flags)
        {
            int users = 0;
            //looking for users who entered yesterday
            List<string> usersLoginToday = new List<string>();
            foreach (var flag in flags)
            {
                if (flag.Login)
                    usersLoginToday.Add(flag.UserId);
            }
            foreach (var flag in flags)
            {
                if (!flag.Login && !usersLoginToday.Exists(u => u.Equals(flag.UserId)))
                    users++;
            }  
            int maxUsers = users;
            //looking for the greatest number of concurrently logged 
            foreach (var flag in flags)
            {
                if (flag.Login)
                {
                    users++;
                    if (maxUsers < users)
                        maxUsers = users;
                }
                else
                    users--;
                 
            }
            return maxUsers;
        }
    }
}

Test/Controllers/UserController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test.Models;
using static Test.Models.ViewModels;

namespace Test.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private TestContext db = new TestContext();
        public string GetUsers()
        {
            List<User> users = db.Users.ToList();
            return JsonConvert.SerializeObject(users);
        }
        public string GetMovements()
        {
            List<Movement> movements = db.Movements.ToList();
            return JsonConvert.SerializeObject(movements);
        }
        [HttpPost]
        public string Create([Bind(Exclude = "Id")] User user)
        {
            string msg;
            try
            {
                if (ModelState.IsValid)
                {
                    db.Database.ExecuteSqlCommand("disable trigger Users_Insert on AspNetUsers");
                    db.Users.Add(user);
                    User presentUser = db.Users.
                        Where(u => u.UserName == User.Identity.Name).
                        FirstOrDefault();
                    Movement movement = new Movement
                    {
                        UserName = presentUser.UserName,
                        Date = DateTime.Now,
                        Change = "added account with name " + user.UserName + "."
                    };
                    db.Movements.Add(movement);
                    db.SaveChanges();
                    db.Database.ExecuteSqlCommand("enable trigger Users_Insert on AspNetUsers");
                    db.SaveChanges();
                    msg = "Saved Successfully";
                }
                else
                {
                    msg = "Validation data not successfully";
                }
            }
            catch (Exception ex)
            {
                msg = "Error occured:" + ex.Message;
            }
            return msg;
        }
        [HttpPost]
        public string Edit(User user)
        {
            string msg;
            try
            {
                if (ModelState.IsValid)
                {
                    Movement movement;
                    using (TestContext tempContext = new TestContext())
                    {
                        User oldUser = tempContext.Users.Find(user.Id);
                        User presentUser = tempContext.Users.
                            Where(u => u.UserName == User.Identity.Name).
                            FirstOrDefault();
                        movement = new Movement
                        {
                            UserName = presentUser.UserName,
                            Date = DateTime.Now,
                            Change = "eddit account with name " + oldUser.UserName + " changed:"
                        };
                        if (user.UserName != oldUser.UserName)
                            movement.Change += " user name " + oldUser.UserName + " to " + user.UserName + ",";
                        if (user.firstName != oldUser.firstName)
                            movement.Change += " first name " + oldUser.UserName + " to " + user.UserName + ",";
                        if (user.UserName != oldUser.UserName)
                            movement.Change += " last name " + oldUser.UserName + " to " + user.UserName + ",";
                        if (user.UserName != oldUser.UserName)
                            movement.Change += " password";
                        movement.Change += ".";
                    }
                    db.Database.ExecuteSqlCommand("disable trigger Users_Update on AspNetUsers");
                    db.Entry(user).State = EntityState.Modified;
                    db.Movements.Add(movement);
                    db.SaveChanges();
                    db.Database.ExecuteSqlCommand("enable trigger Users_Update on AspNetUsers");
                    db.SaveChanges();
                    msg = "Saved Successfully";
                }
                else
                {
                    msg = "Validation data not successfully";
                }
            }
            catch (Exception ex)
            {
                msg = "Error occured:" + ex.Message;
            }
            return msg;
        }
        [HttpPost]
        public string Delete(string Id)
        {
            User user = db.Users.
                Include(u => u.Sessions).
                Where(u => u.Id == Id).FirstOrDefault();
            User presentUser = db.Users.
                Where(u => u.UserName == User.Identity.Name).
                FirstOrDefault();
            Movement movement = new Movement
            {
                UserName = presentUser.UserName,
                Date = DateTime.Now,
                Change = "delete account with name " + user.UserName + "."
            };
            db.Database.ExecuteSqlCommand("disable trigger Users_Delete on AspNetUsers");
            db.Movements.Add(movement);
            db.Users.Remove(user);
            db.SaveChanges();
            db.Database.ExecuteSqlCommand("enable trigger Users_Delete on AspNetUsers");
            db.SaveChanges();
            return "Deleted successfully"; 
        }
        
    }
}

Test/Views/Menu/Index.cshtml
@{
    ViewBag.Title = "Main menu";
}

<hr />
<h2>Hello @User.Identity.Name</h2>
<hr />

Test/Views/Menu/Report.cshtml
@{
    ViewBag.Title = "Report";
}
@using (Ajax.BeginForm("ReportOfMonth", "Menu",null, new AjaxOptions {UpdateTargetId = "report", HttpMethod = "Post"}, new { enctype = "multipart/form-data"}))
{
   <input type="text" name="date" class="date-picker" />
   <input type="submit" class="btn btn-outline-info" value="Get report" />
}
<div id="report"></div>
<script type="text/javascript">
    $(document).ready(function () {
        $('.date-picker').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'mm/yy',
            onClose: function (dateText, inst) {
                $(this).datepicker('setDate', new Date(inst.selectedYear, inst.selectedMonth, 1));
            }
        });
    });
</script>

Test/Views/Menu/ReportOfMonth.cshtml
@model IEnumerable<Test.Models.Week>
<table class="reportTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Monday)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaxUsers)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td >
                @Html.DisplayFor(modelItem => item.Monday)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxUsers)
            </td>
        </tr>
    }
</table>

Test/Views/Menu/Users.cshtml
@{
    ViewBag.Title = "Users";
}
<div class="row">
    <div class="col-md-8">
        <table id="listOfUser"></table>
        <div id="jpager"></div>
    </div>
    <div class="col-md-8">
        <table id="movements"></table>
        <div id="jpager2"></div>
    </div>
</div>

<script>
    $(document).ready(function () {
         $("#movements").jqGrid({
        url: '@Url.Action("GetMovements","User")',
        contentType: "application/json",
        datatype: "json",
        loadonce: false,
        colNames: ['Id','Date time', 'User name', 'Changed'],
        colModel: [
            { key: true, hidden: true, name: 'Id', index: 'Id', editable: true },
            { name: 'Date', index: 'Date', width: 120, edittype: 'text', sortable: true, editrules: { date: true } },
            { name: 'UserName', index: 'UserName', width: 75, edittype: 'text'},
            { name: 'Change', index: 'Change', width: 500, edittype: "textarea", editoptions: { row : 15 } },
        ],
        rowNum: 12,
        width: 950,
        pager: '#jpager2',
        loadui: 'disable',
        sortname: 'Date',
        sortorder: "desc",
        caption: "List of movements",
        jsonReader: {
            repeatitems: false,
            root: function (obj) { return obj; },
            page: function (obj) { return 1; },
            total: function (obj) { return 1; },
            records: function (obj) { return obj.length; }
        },
        });
    });
    $(document).ready(function () {
      $("#listOfUser").jqGrid({
        url: '@Url.Action("GetUsers","User")',
        contentType: "application/json",
        datatype: "json",
        loadonce: true,
        colNames: ['Id','User name', 'First name', 'Last name','Password'],
        colModel: [
            { key: true, hidden: true, name: 'Id', index: 'Id' },
            { name: 'UserName', index: 'UserName', width: 150, editable: true, edittype: 'text', editrules: { required: true }, sortable: true},
            { name: 'firstName', index: 'firstName', width: 150, editable: true, edittype: 'text', editrules: { required: true }, sortable: true },
            { name: 'lastName', index: 'lastName', width: 150, editable: true, edittype: 'text', editrules: { required: true }, sortable: true },
            { name: 'Password', index: 'Password', width: 150, editable: true, edittype: 'password', editrules: {required: true }, sortable: true },
        ],
        rowNum: 12,
        rowList: [10, 20, 30],
        width: 950,
        pager: '#jpager',
        loadui: 'disable',
        sortname: 'UserName',
        sortorder: "desc",
        caption: "List of users",
        jsonReader: {
            repeatitems: false,
            root: function (obj) { return obj; },
            page: function (obj) { return 1; },
            total: function (obj) { return 1; },
            records: function (obj) { return obj.length; }
        },
    });
    $("#listOfUser").jqGrid('navGrid', '#jpager', {

        refresh: false,
        add: true, // добавление
        del: true, // удаление
        edit: true, // редактирование
        view: true, // просмотр записи
        viewtext: "Watch",
        viewtitle: "Selected record",
        addtext: "Add",
        edittext: "Edit",
        deltext: "Delete"
    },
        update("edit"), // обновление
        update("add"), // добавление
        update("del") // удаление
    );
    function update(act) {
        return {
            closeAfterAdd: true, // закрыть после добавления
            height: 250,
            width: 400,
            closeAfterEdit: true, // закрыть после редактирования
            reloadAfterSubmit: true, // обновление
            drag: true,
            onclickSubmit: function (params) {
                var list = $("#listOfUser");
                var selectedRow = list.getGridParam("selrow");
                rowData = list.getRowData(selectedRow);
                if (act === "add")
                    params.url = '@Url.Action("Create","User")';
                else if (act === "del")
                    params.url = '@Url.Action("Delete","User")';
                else if (act === "edit")
                    params.url = '@Url.Action("Edit","User")';
            },
            afterSubmit: function (response, postdata) {
                // обновление грида
                $(this).jqGrid('setGridParam', { datatype: 'json' }).trigger('reloadGrid')
                return [true, "", 0]
            }
        };
    };
    });
    function foo() {
        $('#listOfUser').jqGrid('setGridParam', { datatype: 'json' }).trigger('reloadGrid', [{ current: true }])
        $('#movements').jqGrid('setGridParam', { datatype: 'json' }).trigger('reloadGrid')
        setTimeout(foo, 2000);
    }
    $(document).ready(function () {
        foo();
    });
</script>